language: objective-c
osx_image: xcode63
before_install:
  - gem install xcpretty -N
  - gem install cocoapods --pre --quiet
  - pod setup --silent
  - pod repo update --silent
script:
  - pod install
  - pod lib lint --quick ParseUI.podspec
  - pod lib lint --use-libraries ParseUI.podspec
  - set -o pipefail
  - xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUI' -sdk iphonesimulator build | xcpretty -c
  - xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUIDemo' -sdk iphonesimulator build | xcpretty -c
